version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: weekly
    groups:
      grpc-stack:
        patterns:
          - "prost"
          - "prost-*"
          - "tonic"
          - "tonic-*"
